# https://github.com/WhyAskWhy/automated-tickets
# https://github.com/WhyAskWhy/automated-tickets-dev

# MariaDB/MySQL development instance

production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: redmine

development:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: redmine
